---
- name: Backup | Prerequisites | Override default data with user one
  set_fact:
    rsnapshot: "{{ rsnapshot_defaults | combine(rsnapshot, recursive=True) }}"
  tags:
    - always

- include_tasks: master.yml
  when: rsnapshot.master

- include_tasks: slaves.yml
  when: not rsnapshot.master
